[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rdfportal-mcp"
version = "0.1.0"
description = "MCP Servers for using the RDF Portal"
authors = [
    {name = "Akira R. Kinjo"},
]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastmcp>=2.11.0",
    "httpx>=0.28.1",
    "pydantic>=2.0",
    "pyrudof>=0.1.90"
]

[project.urls]
"Homepage" = "https://github.com/arkinjo/RDFPortal-MCP"
"Repository" = "https://github.com/arkinjo/RDFPortal-MCP"

[project.optional-dependencies]
dev = [
    "pytest", # for running tests
    "ruff",   # for linting and formatting
    "black",  # for code formatting
]
