# RDF-Config file for PDB (Protein Data Bank)
endpoint:
  - https://rdfportal.org/backend/pdb/sparql
  - graph:
    - http://rdfportal.org/dataset/pdbj
    - http://rdf.wwpdb.org/schema/pdbx-v50.owl

metadata:
  title: PDB RDF
  description: Protein Data Bank (PDB) is a database of 3D structural data of biological macromolecules including proteins and nucleic acids, determined by X-ray crystallography, NMR spectroscopy, and cryo-electron microscopy
  tags: [Protein Structure, Crystallography, Macromolecule, Structural Biology, X-ray Diffraction, NMR, Cryo-EM]
  provider: wwPDB
  creators:
    - name: PDBj (Protein Data Bank Japan)
      affiliation: Institute for Protein Research, Osaka University
  version: 1.0.0
  issued: 2025-09-30
  licenses:
    - https://creativecommons.org/publicdomain/zero/1.0/

prefix:
  rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
  owl: <http://www.w3.org/2002/07/owl#>
  xsd: <http://www.w3.org/2001/XMLSchema#>
  dcterms: <http://purl.org/dc/terms/>
  pdbx: <http://rdf.wwpdb.org/schema/pdbx-v50.owl#>
  pdb: <http://rdf.wwpdb.org/pdb/>
  identifiers: <http://identifiers.org/>
  uniprot: <http://purl.uniprot.org/uniprot/>
  taxonomy: <http://purl.uniprot.org/taxonomy/>
  pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>

model:
  - Datablock pdb:1WVU:
    - a: pdbx:datablock
    - pdbx:has_entityCategory:
      - entity_category: pdb:1WVU/entityCategory
    - pdbx:has_entryCategory:
      - entry_category: pdb:1WVU/entryCategory
    - pdbx:has_exptlCategory:
      - exptl_category: pdb:1WVU/exptlCategory
    - pdbx:has_refineCategory:
      - refine_category: pdb:1WVU/refineCategory
    - pdbx:has_citationCategory:
      - citation_category: pdb:1WVU/citationCategory
    - pdbx:has_struct_keywordsCategory:
      - struct_keywords_category: pdb:1WVU/struct_keywordsCategory
    - pdbx:has_entity_src_genCategory:
      - entity_src_gen_category: pdb:1WVU/entity_src_genCategory

  - Entity pdb:1WVU/entity/1:
    - a: pdbx:entity
    - pdbx:entity.id: "1"
    - pdbx:entity.type: "polymer"
    - pdbx:entity.pdbx_description: "chitinase C"
    - pdbx:entity.formula_weight: "28497.170"
    - pdbx:entity.pdbx_number_of_molecules: "2"
    - pdbx:entity.src_method: "man"
    - pdbx:referenced_by_entity_poly:
      - entity_poly: pdb:1WVU/entity_poly/1
    - pdbx:referenced_by_struct_asym+:
      - struct_asym: pdb:1WVU/struct_asym/A

  - StructAsym pdb:1WVU/struct_asym/A:
    - a: pdbx:struct_asym
    - pdbx:struct_asym.id: "A"
    - pdbx:struct_asym.entity_id: "1"
    - pdbx:struct_asym.pdbx_blank_PDB_chainid_flag: "N"
    - pdbx:struct_asym.pdbx_modified: "N"
    - pdbx:reference_to_entity:
      - entity: pdb:1WVU/entity/1
    - pdbx:of_datablock:
      - datablock: pdb:1WVU
    - owl:sameAs:
      - same_chain: pdb:1WVU/struct_asym/1,A
    - pdbx:referenced_by_pdbx_sifts_unp_segments:
      - unp_segment: pdb:1WVU/pdbx_sifts_unp_segments/A,1,1,1,O50152

  - UniprotSegment pdb:1WVU/pdbx_sifts_unp_segments/A,1,1,1,O50152:
    - a: pdbx:pdbx_sifts_unp_segments
    - pdbx:pdbx_sifts_unp_segments.asym_id: "A"
    - pdbx:pdbx_sifts_unp_segments.entity_id: "1"
    - pdbx:pdbx_sifts_unp_segments.unp_acc: "O50152"
    - pdbx:pdbx_sifts_unp_segments.identity: "1.000"
    - pdbx:pdbx_sifts_unp_segments.best_mapping: "Y"
    - pdbx:pdbx_sifts_unp_segments.seq_id_start: "1"
    - pdbx:pdbx_sifts_unp_segments.seq_id_end: "265"
    - pdbx:pdbx_sifts_unp_segments.unp_start: "30"
    - pdbx:pdbx_sifts_unp_segments.unp_end: "294"
    - rdfs:seeAlso:
      - uniprot_identifiers: identifiers:uniprot/O50152
    - pdbx:link_to_uniprot:
      - uniprot_uri: uniprot:O50152
    - pdbx:reference_to_struct_asym:
      - struct_asym_ref: pdb:1WVU/struct_asym/A

  - Exptl pdb:1WVU/exptl/1WVU,X-RAY_DIFFRACTION:
    - a: pdbx:exptl
    - pdbx:exptl.entry_id: "1WVU"
    - pdbx:exptl.method: "X-RAY DIFFRACTION"
    - pdbx:exptl.crystals_number: "1"
    - pdbx:reference_to_entry:
      - entry: pdb:1WVU/entry/1WVU
    - pdbx:of_datablock:
      - datablock_ref: pdb:1WVU

  - Refine pdb:1WVU/refine/1WVU,X-RAY_DIFFRACTION:
    - a: pdbx:refine
    - pdbx:refine.entry_id: "1WVU"
    - pdbx:refine.ls_d_res_high: "2.45"
    - pdbx:refine.ls_d_res_low: "35.47"
    - pdbx:refine.ls_R_factor_R_work: "0.17238"
    - pdbx:refine.ls_R_factor_obs: "0.17494"
    - pdbx:refine.ls_number_reflns_obs: "23560"
    - pdbx:refine.pdbx_refine_id: "X-RAY DIFFRACTION"
    - pdbx:refine.correlation_coeff_Fo_to_Fc: "0.954"
    - pdbx:refine.ls_percent_reflns_R_free: "5.1"
    - pdbx:reference_to_entry:
      - entry_ref: pdb:1WVU/entry/1WVU

  - Citation pdb:1WVU/citation/primary:
    - a: pdbx:citation
    - pdbx:citation.country: "UK"
    - pdbx:citation.journal_id_ISSN: "0022-2836"
    - pdbx:citation.journal_id_ASTM: "JMOBAK"
    - dcterms:references:
      - pubmed_identifiers: identifiers:pubmed/16516924
    - pdbx:link_to_pubmed:
      - pubmed_link: pubmed:16516924
    - pdbx:of_datablock:
      - datablock_cite: pdb:1WVU

  - EntitySrcGen pdb:1WVU/entity_src_gen/1,1:
    - a: pdbx:entity_src_gen
    - pdbx:entity_src_gen.entity_id: "1"
    - pdbx:entity_src_gen.gene_src_genus: "Streptomyces"
    - pdbx:entity_src_gen.pdbx_gene_src_scientific_name: "Streptomyces griseus"
    - pdbx:entity_src_gen.pdbx_gene_src_ncbi_taxonomy_id: "1911"
    - pdbx:entity_src_gen.host_org_genus: "Escherichia"
    - pdbx:entity_src_gen.host_org_species: "Escherichia coli"
    - pdbx:entity_src_gen.pdbx_host_org_scientific_name: "Escherichia coli BL21(DE3)"
    - pdbx:entity_src_gen.pdbx_host_org_ncbi_taxonomy_id: "469008"
    - pdbx:entity_src_gen.pdbx_host_org_strain: "BL21(DE3)"
    - pdbx:entity_src_gen.plasmid_name: "pET12a"
    - pdbx:entity_src_gen.pdbx_host_org_vector_type: "PLASMID"
    - rdfs:seeAlso:
      - taxonomy_source: identifiers:taxonomy/1911
      - taxonomy_host: identifiers:taxonomy/469008
    - pdbx:link_to_taxonomy_source:
      - taxonomy_source_uri: taxonomy:1911
    - pdbx:link_to_taxonomy_host:
      - taxonomy_host_uri: taxonomy:469008
    - pdbx:reference_to_entity:
      - entity_ref: pdb:1WVU/entity/1

  - StructKeywords pdb:1WVU/struct_keywords/1WVU:
    - a: pdbx:struct_keywords
    - pdbx:struct_keywords.entry_id: "1WVU"
    - pdbx:struct_keywords.pdbx_keywords: "HYDROLASE"
    - pdbx:struct_keywords.text: "family 19 chitinase, whole structure, HYDROLASE"
    - pdbx:reference_to_entry:
      - entry_keywords: pdb:1WVU/entry/1WVU

  - StructConf pdb:1WVU/struct_conf/HELX_P1:
    - a: pdbx:struct_conf
    - pdbx:of_datablock:
      - datablock_conf: pdb:1WVU
